language: python
python:
  - "3.5.2"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE hello_books;" -U prince
  - psql -c "CREATE USER prince WITH PASSWORD 'prince'; -U prince

script: 
  - nosetests --with-coverage

after_success:
  - coveralls
  - codeclimate-test-reporter


